name: Azure Static Web Apps - Next.js

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # (Optional) Install deps first to speed up the SWA action's build cache
      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Enables PR comments
          action: "upload"
          #### Paths in your repo
          app_location: "/"
          api_location: "api"
          output_location: ".next"
          #### If you keep Next.js images in /public, that's fine; no extra config needed
        env:
          NEXT_TELEMETRY_DISABLED: 1
          # If you need environment variables at build time, add them here:
          # NEXT_PUBLIC_API_BASE: "https://example.com"

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"